AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  BucketName:
    Description: Unique name for your bucket. This will be in the S3 url to your React app.
    Type: String

Resources:
  # Create an S3 Bucket With cloudFront
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private 
      Tags:
        - Key: my
          Value: react app
  

  # Add a Bucket Policy that lets public visitors access the web app
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket # attach to bucket being created
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}" 
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MyBucket, /*]]
   
  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "origin identity"

  PublicDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt MyBucket.DomainName
            Id: !Sub S3-${MyBucket}
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginIdentity}"
        Enabled: "true"
        DefaultRootObject: index.html
        Comment: CloudFront::Distribution
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD

          TargetOriginId: !Sub S3-${MyBucket}
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: "allow-all"
        ViewerCertificate:
          CloudFrontDefaultCertificate: "true"
        CustomErrorResponses:
          - ErrorCode: "404"
            ResponsePagePath: "/index.html"
            ResponseCode: "200"
            ErrorCachingMinTTL: "0"
Outputs:
  WebsiteURL:
    Value: !GetAtt MyBucket.WebsiteURL
    Description: URL for website hosted on S3