version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '8081:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./logs/nginx:/var/log/nginx
            - ./wordpress:/var/www/html
        links:
            - wordpress
        restart: always 
    mysql:
        image: mariadb
        #ports:
            #- '3306:3306'
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysqldb
            MYSQL_PASSWORD: user_pass
            MYSQL_USER: user_name
        restart: always 
    wordpress:
        image: wordpress:4.7.1-php7.0-fpm
        ports:
            - '9000:9000'
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_NAME: mysqldb
            WORDPRESS_DB_USER: user_name
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_PASSWORD: user_pass
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        links:
            - mysql
        restart: always
volumes:
    mysql: